[package]
name = "reudh"
version = "0.1.0"
authors = ["Ben Weedon <ben.weedon@outlook.com>"]

[dependencies]
futures = "0.1.18"
html5ever = "0.22.0"
hyper = "0.11.16"
hyper-tls = "0.1.2"
tokio-core = "0.1.12"
